version: "3"
services:
  # prod Image
  blokkers:
    build:
      context: .
      dockerfile: ./docker/prod_image/Dockerfile
    image: blokkers:local
    ports:
      - "8080:8080" # Remember, this must correspond to the environmental variable file.
    container_name: blokkers
    volumes: # Only mounted if run by docker-compose up
      - ./app/src:/app/src
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1m"
