--- 
networks: 
  app-network: 
    driver: bridge
services: 
  certbot: 
    command: "certonly --webroot --webroot-path=/var/www/html --email aaron.aa@me.com --agree-tos --no-eff-email --force-renewal -d blokkers.dk  -d www.blokkers.dk"
    container_name: certbot
    depends_on: 
      - webserver
    image: certbot/certbot
    volumes: 
      - "certbot-etc:/etc/letsencrypt"
      - "certbot-var:/var/lib/letsencrypt"
      - "web-root:/var/www/html"
  nodejs: 
    build: 
      context: "."
      dockerfile: Dockerfile
    container_name: blokkers-app
    image: blokkers-app
    networks: 
      - app-network
    restart: unless-stopped
  webserver: 
    container_name: webserver
    depends_on: 
      - nodejs
    image: "nginx:mainline-alpine"
    networks: 
      - app-network
    ports: 
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes: 
      - "web-root:/var/www/html"
      - "./nginx-conf:/etc/nginx/conf.d"
      - "certbot-etc:/etc/letsencrypt"
      - "certbot-var:/var/lib/letsencrypt"
      - "dhparam:/etc/ssl/certs"
version: "3.8"
volumes: 
  certbot-etc: ~
  certbot-var: ~
  dhparam: 
    device: /home/aaron/blokkers/app/dhparam/
    driver: local
    type: none
    driver_opts: ~
    o: bind 
  web-root: 
    driver: local
    driver_opts:
      type: none
      device: /home/aaron/blokkers/app/public
      o: bind
      
