version: "3"
services:
  # prod Image
  blokkers:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: blokkers:local
    ports:
      
      - "8080:8080" # Remember, this must correspond to the environmental variable file.
   
    container_name: blokkers
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1m"
    volumes:
      - ./app/src:/app/src

# ./docker/prod_image/Dockerfile


