
events {
    worker_connections  4096;  ## Default: 1024
}
http {

    server {
listen 80;
server_name blokkers.dk www.blokkers.dk;
root /var/www/html;

charset UTF-8;

error_page 404 /backend-not-found.html;
location = /backend-not-found.html {
allow   all;
}



}
}